winget install --id Git.Git -e --source winget
winget install --id DuongDieuPhap.ImageGlass --source winget
winget install --id 7zip.7zip --source winget
Winget install --id Mozilla.Firefox --source winget
winget install --id Meta.Oculus --source winget
winget install --id Logitech.GHUB --source winget
winget install --id Eraser.Eraser --source winget
winget install --id Valve.Steam --source winget
winget install --id qBittorrent.qBittorrent --source winget
winget install --id Discord.Discord --source winget
winget install --id DominikReichl.KeePass --source winget
winget install --id Nextcloud.NextcloudDesktop --source winget
winget install --id AntibodySoftware.WizTree --source winget
winget install --id WinSCP.WinSCP --source winget
winget install --id CPUID.CPU-Z --source winget
winget install --id Bitwarden.Bitwarden --source winget
winget install --id ShareX.ShareX --source winget
winget install --id Guru3D.Afterburner --source winget
winget install --id WireGuard.WireGuard --source winget
